version: 2
updates:
# Create PRs for golang version updates
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  ignore:
    - dependency-name: "golang"
      versions: ["*-rc*"]
